  export const pricing = [
    {
      name: "baCkpaCkEr",
      price: "frEE",
      description: "Perfect for casual travelers",
      monthlyPrice: 0,
      annualPrice: 0,
      features: [
        "Up to 5 trips per year",
        "Basic itinerary planning",
        "Mobile app access",
        "Community forum access",
        "Email support",
        "Standard maps and navigation",
      ],
      highlighted: false,
    },
    {
      name: "glObEtrOttEr",
      price: "$7.99",
      period: "/month",
      description: "For frequent adventures",
      monthlyPrice: 7.99,
      annualPrice: 79.99,
      features: [
        "Unlimited trips",
        "Advanced itinerary planning",
        "Offline map downloads",
        "AI trip recommendations",
        "Priority email support",
        "Travel budget tracking",
        "Collaboration with friends",
        "Photo gallery storage (5GB)",
      ],
      highlighted: true,
    },
    {
      name: "nOmad",
      price: "$11.99",
      period: "/month",
      description: "The ultimate travel experience",
      monthlyPrice: 11.99,
      annualPrice: 119.99,
      features: [
        "Everything in Globetrotter",
        "Offline access to all features",
        "Live chat support (24/7)",
        "Premium AI insights",
        "Photo gallery storage (100GB)",
        "Custom trip templates",
        "Travel insurance quotes",
        "VIP community access",
        "Monthly travel magazine",
        "Exclusive travel deals",
      ],
      highlighted: false,
    },
  ];