import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/ui/navbar/Navbar";
import { SubPlanProvider } from "@/components/context/SubPlanContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import AuthProvider from "@/components/auth/AuthProvider";
import ReloadToTop from "@/components/utils/ReloadToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head suppressHydrationWarning />
      <body>
        <div id="__app">
          <Navbar />
          <SubPlanProvider>
            <AuthProvider>
              <ReloadToTop />
                {children}
            </AuthProvider>
          </SubPlanProvider>
          <ToastContainer position="top-center" theme="dark" />
        </div>
      </body>
    </html>
  );
}