import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SubPlanProvider } from "@/components/context/SubPlanContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SubPlanProvider>
          <Navbar />
          {children}
        </SubPlanProvider>
      </body>
    </html>
  );
}
